//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class EmoticonBoardPageSectionInfo, EmoticonBoardPageWrap, NSArray, NSDictionary, NSString, UICollectionView, UICollectionViewFlowLayout;

@interface EmoticonBoardPageCollectionController : MMObject <UICollectionViewDelegate, UICollectionViewDataSource, UIGestureRecognizerDelegate>
{
    UICollectionView *m_collectionView;
    UICollectionViewFlowLayout *m_collectionLayout;
    NSArray *m_sectionInfoArray;
    NSDictionary *m_sectionInfoDic;
    unsigned int m_lastCheckSectionInfoIndex;
    EmoticonBoardPageSectionInfo *m_curSectionInfo;
    float m_curSectionStartOffset;
    unsigned int m_emoticonCountPerPage;
    id <EmoticonBoardPageCollectionControllerDelegate><QQEmojiGridViewDelegate><EmoticonGridViewDelegate><EmoticonBoardRecommendViewDelegate> _delegate;
}

@property(nonatomic) __weak id <EmoticonBoardPageCollectionControllerDelegate><QQEmojiGridViewDelegate><EmoticonGridViewDelegate><EmoticonBoardRecommendViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)forceChangeToPid:(id)arg1 backupSectionNum:(unsigned int)arg2 firstPage:(BOOL)arg3;
- (void)scrollToCurrentPage;
- (BOOL)updateSectionInfo:(id)arg1;
- (id)sectionInfoForPid:(id)arg1;
- (void)onStopAtSectionInfo:(id)arg1 offSet:(float)arg2;
- (void)adjustCurSectionInfoAtSectionNum:(unsigned int)arg1 forceAdjust:(BOOL)arg2;
- (void)updateViewSettingWithFrame:(struct CGRect)arg1;
- (void)configViewSettingWithFrame:(struct CGRect)arg1;
- (void)scrollToPageInCurSection:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)changePageToPid:(id)arg1;
@property(readonly, nonatomic) EmoticonBoardPageWrap *curPageWrap;
@property(readonly, nonatomic) UICollectionView *collectionView;
- (void)setEmoticonPageArray:(id)arg1;
- (void)updateCollectionViewFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

