//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class GetGameIndex2Response_Recommendation;

@interface GameCenterRecommendView : MMUIView
{
    GetGameIndex2Response_Recommendation *_recoBanner;
    id <GameCenterRecommendViewDelegate> _delegate;
}

+ (float)heightForRecommendData:(id)arg1;
@property(nonatomic) __weak id <GameCenterRecommendViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onLowerRightItemClicked:(id)arg1;
- (void)onLowerLeftItemClicked:(id)arg1;
- (void)onUpperBgBtnClicked:(id)arg1;
- (id)genLabelWithBoldFontSize:(float)arg1 text:(id)arg2 textColor:(id)arg3 x:(float)arg4 y:(float)arg5 maxWidth:(float)arg6 superView:(id)arg7;
- (id)genLabelWithFontSize:(float)arg1 text:(id)arg2 textColor:(id)arg3 x:(float)arg4 y:(float)arg5 maxWidth:(float)arg6 superView:(id)arg7;
- (float)getLowerTitleFontSize;
- (void)addRecomendItem:(id)arg1 IsLeft:(BOOL)arg2 SuperView:(id)arg3;
- (id)setupLowerView;
- (float)getUpperTitleMaxWidth;
- (id)getFriendUserHead:(id)arg1;
- (id)getFriendListView:(id)arg1 MaxWidth:(float)arg2;
- (id)setupUpperView;
- (void)setupViews;
- (id)initWithFrame:(struct CGRect)arg1 recommendData:(id)arg2;

@end

