//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "MMWebImageViewDelegate.h"

@class GameCenterGameBriefInfo, GameIndexMyGame_Game, NSMutableSet, NSString;

@interface GameCenterMyGameView : MMUIView <MMWebImageViewDelegate>
{
    GameIndexMyGame_Game *_gameItem;
    int _sourceScene;
    NSMutableSet *_gameRectangleIconSet;
    NSMutableSet *_gameRectangleIconNeedCenter;
    float _moduleSubTileOriginX;
    GameCenterGameBriefInfo *_gameInfo;
    BOOL _bShouldUseHvAppInfo;
    id <GameCenterMyGameViewDelegate> _delegate;
    int _index;
}

+ (id)genLabelWithFontSize:(float)arg1 text:(id)arg2 textColor:(id)arg3 x:(float)arg4 y:(float)arg5 maxWidth:(float)arg6 superView:(id)arg7;
+ (struct CGSize)getTextTplPicSize:(id)arg1;
+ (struct CGSize)getTplPicSize:(id)arg1;
+ (id)getTextTplSubView:(id)arg1;
+ (id)getVideoTplSubView:(id)arg1;
+ (id)getPicTplSubView:(id)arg1;
+ (float)getHeightForTpl:(id)arg1;
+ (float)heightForData:(id)arg1;
@property(readonly, nonatomic) int index; // @synthesize index=_index;
@property(nonatomic) __weak id <GameCenterMyGameViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onLoadImageOKNeedCenter:(id)arg1;
- (void)onLoadImageOK:(id)arg1;
- (void)onLoadImageOKNeedSquare:(id)arg1;
- (void)onTplClicked:(id)arg1;
- (void)onGameRowClicked:(id)arg1;
- (void)onDownloadButtonClicked:(id)arg1;
- (id)createPicViewInVideoTpl:(id)arg1;
- (id)createPicViewInTextTpl:(id)arg1;
- (id)createHeadView;
- (float)getModuleTitleMaxWidth:(id)arg1;
- (id)getTplView:(id)arg1;
- (void)setupView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 recentGameInfo:(id)arg2 index:(int)arg3 SourceScene:(int)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

