//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPUImageFilterGroup.h"

@class GPUImageBilateralFilterCustom, GPUImageBrightnessRefineFilter, GPUImageRawDataInput;

@interface GPUImageLightBoostFilter : GPUImageFilterGroup
{
    GPUImageBrightnessRefineFilter *brightnessRefineFilter;
    GPUImageBilateralFilterCustom *bilateralFilter;
    GPUImageRawDataInput *rawDataCurveInputFilter;
    unsigned int image_width;
    unsigned int image_height;
    unsigned char _meanGray;
    unsigned char _meanGrayTH;
    BOOL _grayLowFlag;
    unsigned char _lowLightCountTH;
    unsigned int _lightBoostEnable;
    unsigned int _deNoiseEnable;
    float _maxRatioTH;
    float _maxOffsetTH;
    CDUnknownBlockType _frameBrightnessDidChangeBlock;
}

@property(copy, nonatomic) CDUnknownBlockType frameBrightnessDidChangeBlock; // @synthesize frameBrightnessDidChangeBlock=_frameBrightnessDidChangeBlock;
@property(nonatomic) float maxOffsetTH; // @synthesize maxOffsetTH=_maxOffsetTH;
@property(nonatomic) float maxRatioTH; // @synthesize maxRatioTH=_maxRatioTH;
@property(nonatomic) unsigned int deNoiseEnable; // @synthesize deNoiseEnable=_deNoiseEnable;
@property(nonatomic) unsigned int lightBoostEnable; // @synthesize lightBoostEnable=_lightBoostEnable;
@property(nonatomic) unsigned char lowLightCountTH; // @synthesize lowLightCountTH=_lowLightCountTH;
@property(nonatomic) BOOL grayLowFlag; // @synthesize grayLowFlag=_grayLowFlag;
@property(nonatomic) unsigned char meanGrayTH; // @synthesize meanGrayTH=_meanGrayTH;
@property(nonatomic) unsigned char meanGray; // @synthesize meanGray=_meanGray;
- (void).cxx_destruct;
- (void)reset;
- (void)updateCurveIndex;
- (void)notifyMoonStyle:(BOOL)arg1;
- (id)init;

@end

