//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MMHeadImageView, UIButton, UIImageView, UILabel, WCPayBindCardInfo, WCPayControlData;

@interface HoneyPayReceiverCardView : UIView
{
    id <HoneyPayReceiverCardViewDelegate> _delegate;
    WCPayBindCardInfo *_info;
    WCPayControlData *_data;
    UIButton *_button;
    UIView *_contentView;
    UIImageView *_arcImageView;
    MMHeadImageView *_avatar;
    UILabel *_nameLabel;
    UILabel *_typeLabel;
    UILabel *_balanceLabel;
    UILabel *_balanceTipLabel;
}

@property(retain, nonatomic) UILabel *balanceTipLabel; // @synthesize balanceTipLabel=_balanceTipLabel;
@property(retain, nonatomic) UILabel *balanceLabel; // @synthesize balanceLabel=_balanceLabel;
@property(retain, nonatomic) UILabel *typeLabel; // @synthesize typeLabel=_typeLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) MMHeadImageView *avatar; // @synthesize avatar=_avatar;
@property(retain, nonatomic) UIImageView *arcImageView; // @synthesize arcImageView=_arcImageView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(retain, nonatomic) WCPayControlData *data; // @synthesize data=_data;
@property(retain, nonatomic) WCPayBindCardInfo *info; // @synthesize info=_info;
@property(nonatomic) __weak id <HoneyPayReceiverCardViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)click;
- (void)layout;
- (id)initWithInfo:(id)arg1 data:(id)arg2;

@end

