//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MMAudioDataReadStreamDelegate.h"
#import "UIAlertViewDelegate.h"

@class MMAudioDataPipe, NSDictionary, NSNotificationCenter, NSString, NSThread;

@interface MMAudioStreamPlayer : NSObject <MMAudioDataReadStreamDelegate, UIAlertViewDelegate>
{
    MMAudioDataPipe *m_dataPipe;
    struct OpaqueAudioQueue *audioQueue;
    struct OpaqueAudioFileStreamID *audioFileStream;
    struct AudioStreamBasicDescription asbd;
    NSThread *internalThread;
    struct AudioQueueBuffer *audioQueueBuffer[16];
    struct AudioStreamPacketDescription packetDescs[512];
    unsigned int fillBufferIndex;
    unsigned long packetBufferSize;
    unsigned long bytesFilled;
    unsigned long packetsFilled;
    _Bool inuse[16];
    int buffersUsed;
    int state;
    int stopReason;
    int errorCode;
    long err;
    _Bool discontinuous;
    struct _opaque_pthread_mutex_t queueBuffersMutex;
    struct _opaque_pthread_cond_t {
        long __sig;
        char __opaque[24];
    } queueBufferReadyCondition;
    NSNotificationCenter *notificationCenter;
    unsigned long bitRate;
    int dataOffset;
    int fileLength;
    unsigned long long audioDataByteCount;
    unsigned long long processedPacketsCount;
    unsigned long long processedPacketsSizeTotal;
    double seekTime;
    BOOL seekWasRequested;
    double requestedSeekTime;
    double sampleRate;
    double packetDuration;
    double lastProgress;
    BOOL pausedByInterruption;
    NSDictionary *streamProperties;
}

+ (unsigned long)hintForFileExtension:(id)arg1;
+ (id)stringForErrorCode:(int)arg1;
@property(readonly) NSDictionary *streamProperties; // @synthesize streamProperties;
@property unsigned long bitRate; // @synthesize bitRate;
@property int errorCode; // @synthesize errorCode;
- (void).cxx_destruct;
- (void)handleInterruptionChangeToState:(unsigned long)arg1;
- (void)handlePropertyChangeForQueue:(struct OpaqueAudioQueue *)arg1 propertyID:(unsigned long)arg2;
- (void)handleBufferCompleteForQueue:(struct OpaqueAudioQueue *)arg1 buffer:(struct AudioQueueBuffer *)arg2;
- (void)handleAudioPackets:(const void *)arg1 numberBytes:(unsigned long)arg2 numberPackets:(unsigned long)arg3 packetDescriptions:(struct AudioStreamPacketDescription *)arg4;
- (void)handlePropertyChangeForFileStream:(struct OpaqueAudioFileStreamID *)arg1 fileStreamPropertyID:(unsigned long)arg2 ioFlags:(unsigned int *)arg3;
- (void)createQueue;
- (void)enqueueBuffer;
- (void)handleReadFromStream:(id)arg1 eventType:(unsigned long)arg2;
- (struct OpaqueAudioQueue *)getAudioQueue;
- (void)stop;
- (void)pause;
@property(readonly) double duration;
- (double)calculatedBitRate;
@property(readonly) double progress;
- (void)seekToTime:(double)arg1;
- (void)internalSeekToTime:(double)arg1;
- (void)start;
- (void)startInternal;
- (BOOL)isIdle;
- (BOOL)isPaused;
- (BOOL)isPlaying;
- (BOOL)isWaiting;
@property int state; // @synthesize state;
- (void)mainThreadStateNotification;
- (void)failWithErrorCode:(int)arg1;
- (void)reportError:(int)arg1;
- (void)presentAlertWithTitle:(id)arg1 message:(id)arg2;
- (void)onHandleReadEventfromStream:(id)arg1 eventType:(unsigned long)arg2;
- (BOOL)runLoopShouldExit;
- (BOOL)isFinishing;
- (void)dealloc;
- (id)initWithDataPipe:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

