//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IMMDumpReporterMgrExt.h"
#import "MMPickerViewDelegate.h"

@class MMPickerView, MMProgressView, NSMutableArray, NSString, UIButton, UIImageView, UILabel, UIScrollView, UISwitch, UITextField, UIView;

@interface MMCheckDumpViewController : MMUIViewController <IMMDumpReporterMgrExt, MMPickerViewDelegate>
{
    UITextField *m_textFiled;
    unsigned int m_nTimeInterval;
    NSMutableArray *m_arrDates;
    int m_selectedRow;
    UIView *roundView;
    UILabel *m_tipLabel;
    UILabel *m_checklabel;
    UISwitch *m_checkSitchView;
    UIButton *m_btnDate;
    UIButton *m_btndump;
    UILabel *m_warningLabel;
    UIImageView *m_imgvRecover;
    MMPickerView *m_pickerView;
    UIButton *m_btnTestDBCorrupt;
    UIButton *m_btnTestFrameDrop;
    UIScrollView *m_mainScrollView;
    MMProgressView *m_progressView;
    _Bool m_isUploading;
    _Bool m_isFinish;
}

- (void).cxx_destruct;
- (void)onProgress:(float)arg1;
- (void)onUploadResult:(BOOL)arg1;
- (void)MMPickerViewDidChooseRow:(int)arg1 atSession:(int)arg2;
- (void)testFrameDropDump;
- (void)testDBCorruptDump;
- (void)onChoseDate;
- (void)onUploadDump;
- (void)onSwitchValueChange:(id)arg1;
- (void)initData;
- (void)makeProgressView;
- (void)makeTipLabelWithText:(id)arg1;
- (void)makeIconView;
- (void)makeScrollView;
- (void)makeUploadSuccessView;
- (void)makeUploadingView;
- (void)makeInitView;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

