//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "QRecyclableView.h"
#import "QSMCalloutViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSString, QSMCalloutView, UIImage, UILongPressGestureRecognizer, UITapGestureRecognizer;

@interface QAnnotationView : UIView <UIGestureRecognizerDelegate, QRecyclableView, QSMCalloutViewDelegate>
{
    BOOL highlighted;
    BOOL _selected;
    BOOL selectedBeforeStarting;
    BOOL canShowCallout;
    BOOL draggable;
    NSString *_reuseIdentifier;
    id <QAnnotation> _annotation;
    UIView *_leftCalloutAccessoryView;
    UIView *_rightCalloutAccessoryView;
    QSMCalloutView *tip;
    int _dragState;
    UITapGestureRecognizer *tapGestureGecognizer;
    UILongPressGestureRecognizer *longPressGestureGecognizer;
    UITapGestureRecognizer *_tapTwiceGestureGecognizer;
    struct CGPoint _centerOffset;
    struct CGPoint calloutOffset;
}

@property(retain, nonatomic) UITapGestureRecognizer *tapTwiceGestureGecognizer; // @synthesize tapTwiceGestureGecognizer=_tapTwiceGestureGecognizer;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureGecognizer; // @synthesize longPressGestureGecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureGecognizer; // @synthesize tapGestureGecognizer;
@property(nonatomic) int dragState; // @synthesize dragState=_dragState;
@property(nonatomic, getter=isDraggable) BOOL draggable; // @synthesize draggable;
@property(retain, nonatomic) QSMCalloutView *tip; // @synthesize tip;
@property(retain, nonatomic) UIView *rightCalloutAccessoryView; // @synthesize rightCalloutAccessoryView=_rightCalloutAccessoryView;
@property(retain, nonatomic) UIView *leftCalloutAccessoryView; // @synthesize leftCalloutAccessoryView=_leftCalloutAccessoryView;
@property(nonatomic) struct CGPoint calloutOffset; // @synthesize calloutOffset;
@property(nonatomic) BOOL canShowCallout; // @synthesize canShowCallout;
@property(nonatomic) BOOL selectedBeforeStarting; // @synthesize selectedBeforeStarting;
@property(nonatomic, getter=isSelected) BOOL selected; // @synthesize selected=_selected;
@property(nonatomic, getter=isHighlighted) BOOL highlighted; // @synthesize highlighted;
@property(nonatomic) struct CGPoint centerOffset; // @synthesize centerOffset=_centerOffset;
@property(retain, nonatomic) id <QAnnotation> annotation; // @synthesize annotation=_annotation;
@property(copy, nonatomic) NSString *reuseIdentifier; // @synthesize reuseIdentifier=_reuseIdentifier;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithAnnotation:(id)arg1 reuseIdentifier:(id)arg2;
- (void)initGestureRecognizers;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)removeFromSuperview;
- (void)longPressGesture:(id)arg1;
- (void)tapTwiceGesture:(id)arg1;
- (void)tapGesture:(id)arg1;
- (void)hideTipAnimated:(BOOL)arg1;
- (void)showTipAnimated:(BOOL)arg1;
- (void)setDragState:(int)arg1 animated:(BOOL)arg2;
- (BOOL)supportDragOperation;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
@property(nonatomic, getter=isEnabled) BOOL enabled;
- (void)prepareForReuse;
@property(retain, nonatomic) UIImage *image;
- (void)calloutAccessoryAction:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (double)calloutView:(id)arg1 delayForRepositionWithSize:(struct CGSize)arg2;
- (void)removeObserverForAnnotation:(id)arg1;
- (void)addObserverForAnnotation:(id)arg1;
- (void)removeTargetForControl:(id)arg1;
- (void)addTargetForControl:(id)arg1;
- (void)animationWithDuration:(double)arg1 delay:(double)arg2 coordinates:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)notifyCalloutAccessoryControlTapped:(id)arg1;
- (void)notifyDidChangeDragState:(int)arg1 fromOldState:(int)arg2;
- (void)notifyDidDeselect;
- (void)notifyDidSelect;
- (struct CLLocationCoordinate2D)coordinateForPoint:(struct CGPoint)arg1;
- (void)updateCenter;
- (id)container;
- (id)mapView;
- (id)annotationFloor;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

