//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QDataSourceBase.h"

@interface QDataSourceStandard : QDataSourceBase
{
    BOOL _isHandDrawMapEnabled;
}

+ (id)dataSourceStandard:(id)arg1 version:(id)arg2;
+ (id)dataSourceStandard:(id)arg1;
@property(nonatomic) BOOL isHandDrawMapEnabled; // @synthesize isHandDrawMapEnabled=_isHandDrawMapEnabled;
- (int)tileType;
- (BOOL)shouldCollectRequestTime;
- (BOOL)putCacheData:(id)arg1;
- (id)getCacheData:(id)arg1;
- (id)tilePath:(CDStruct_6f177a0f)arg1 info:(id)arg2;
- (float)tileSize;

// Remaining properties
@property(retain, nonatomic) id <QDataCacheProtocol> dataCache;

@end

