//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QDataSourceBase.h"

@interface QDataSourceWorldmapStandard : QDataSourceBase
{
}

+ (id)dataSourceStandard:(id)arg1 version:(id)arg2;
+ (id)dataSourceStandard:(id)arg1;
- (id)tilePath:(CDStruct_6f177a0f)arg1 info:(id)arg2;
- (float)tileSize;
- (id)TileXYToQuadKey:(CDStruct_6f177a0f)arg1;
- (int)tileType;
- (BOOL)shouldCollectRequestTime;
- (void)setMapLanguage:(unsigned int)arg1;
- (id)lauguageCode;
- (id)initWithStyleId:(id)arg1 version:(id)arg2;

@end

