//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface QDataCacheItem : NSObject
{
    BOOL _shouldUpdateData;
    int _sourceType;
    NSData *_tileData;
    NSString *_cacheStyleid;
    NSString *_cacheVersion;
    NSString *_tileVersion;
    NSString *_tileSignature;
    NSString *_language;
    CDStruct_6f177a0f _tile;
}

@property(retain, nonatomic) NSString *language; // @synthesize language=_language;
@property(retain, nonatomic) NSString *tileSignature; // @synthesize tileSignature=_tileSignature;
@property(retain, nonatomic) NSString *tileVersion; // @synthesize tileVersion=_tileVersion;
@property(retain, nonatomic) NSString *cacheVersion; // @synthesize cacheVersion=_cacheVersion;
@property(retain, nonatomic) NSString *cacheStyleid; // @synthesize cacheStyleid=_cacheStyleid;
@property(nonatomic) BOOL shouldUpdateData; // @synthesize shouldUpdateData=_shouldUpdateData;
@property(retain, nonatomic) NSData *tileData; // @synthesize tileData=_tileData;
@property(nonatomic) CDStruct_6f177a0f tile; // @synthesize tile=_tile;
@property(nonatomic) int sourceType; // @synthesize sourceType=_sourceType;
- (void).cxx_destruct;

@end

