//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDictionary, NSString, NSURL, UIImage;

@protocol QDataSourceProtocol <NSObject>
@property(readonly, nonatomic) float tileSize;
- (NSData *)tileData:(CDStruct_6f177a0f)arg1;

@optional
@property(nonatomic) unsigned int mapLanguage;
@property(readonly, nonatomic) int maxZoomLevel;
@property(readonly, nonatomic) int minZoomLevel;
- (UIImage *)tileImage:(CDStruct_6f177a0f)arg1 needFresh:(char *)arg2;
- (NSURL *)tileURL:(CDStruct_6f177a0f)arg1 info:(NSDictionary *)arg2;
- (NSString *)tilePath:(CDStruct_6f177a0f)arg1 info:(NSDictionary *)arg2;
@end

