//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class QMapView;

@interface QOverlayFloor : UIView
{
    QMapView *_mapView;
}

@property(nonatomic) __weak QMapView *mapView; // @synthesize mapView=_mapView;
- (void).cxx_destruct;
- (id)initWithMapView:(id)arg1;
- (void)updateOverlayView:(id)arg1 animated:(BOOL)arg2 animateDuraton:(double)arg3;
- (void)updateOverlayView:(id)arg1 animated:(BOOL)arg2;
- (void)updateOverlayViewsWithAnimated:(BOOL)arg1;
- (void)updateOverlayView:(id)arg1 scaleRelative20:(float)arg2 animated:(BOOL)arg3 animationDuration:(double)arg4;
- (float)scaleRelative20;
- (double)animationDurationOfBoundsProperty;

@end

