//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QAnnotationView.h"

@class UIImageView;

@interface QPinAnnotationView : QAnnotationView
{
    BOOL _animatesDrop;
    int _pinColor;
    UIImageView *_shadowImageView;
    struct CGRect _validRect;
}

@property(nonatomic) struct CGRect validRect; // @synthesize validRect=_validRect;
@property(nonatomic) BOOL animatesDrop; // @synthesize animatesDrop=_animatesDrop;
@property(retain, nonatomic) UIImageView *shadowImageView; // @synthesize shadowImageView=_shadowImageView;
@property(nonatomic) int pinColor; // @synthesize pinColor=_pinColor;
- (void).cxx_destruct;
- (id)initWithAnnotation:(id)arg1 reuseIdentifier:(id)arg2;
- (void)setDragState:(int)arg1 animated:(BOOL)arg2;
- (void)willMoveToSuperview:(id)arg1;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)changeToLift:(BOOL)arg1;
- (id)dropAnimationWithFromPoint:(struct CGPoint)arg1 completion:(CDUnknownBlockType)arg2;
- (id)shadowAnimationFromPoint:(struct CGPoint *)arg1 toPoint:(struct CGPoint *)arg2 duration:(double)arg3 completion:(CDUnknownBlockType)arg4;
- (id)liftImageForPinColor:(int)arg1;
- (id)imageForPinColor:(int)arg1;

@end

