//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class NSMutableArray, QQEmojiViewWithPreview;

@interface QQEmojiGridView : MMUIView
{
    NSMutableArray *m_emoticonWrapArray;
    int m_column;
    int m_row;
    NSMutableArray *m_emoticonViewArray;
    float m_itemWidth;
    float m_itemHeight;
    float m_edgeTop;
    float m_edgeLeft;
    float m_intervalX;
    float m_intervalY;
    QQEmojiViewWithPreview *m_deleteButton;
    id <QQEmojiGridViewDelegate> m_delegate;
}

+ (unsigned int)countPerPageForSize:(struct CGSize)arg1;
@property(nonatomic) __weak id <QQEmojiGridViewDelegate> m_delegate; // @synthesize m_delegate;
@property(nonatomic) float m_intervalY; // @synthesize m_intervalY;
@property(nonatomic) float m_intervalX; // @synthesize m_intervalX;
@property(nonatomic) float m_edgeLeft; // @synthesize m_edgeLeft;
@property(nonatomic) float m_edgeTop; // @synthesize m_edgeTop;
@property(nonatomic) float m_itemHeight; // @synthesize m_itemHeight;
@property(nonatomic) float m_itemWidth; // @synthesize m_itemWidth;
@property(nonatomic) int m_row; // @synthesize m_row;
@property(nonatomic) int m_column; // @synthesize m_column;
@property(retain, nonatomic) NSMutableArray *m_emoticonViewArray; // @synthesize m_emoticonViewArray;
@property(retain, nonatomic) NSMutableArray *m_emoticonWrapArray; // @synthesize m_emoticonWrapArray;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (int)getRealIndexFromPoint:(struct CGPoint)arg1;
- (void)onLongPressOnEmoticon:(id)arg1;
- (void)reloadData;
- (void)calculateLayout;
- (id)cellKey;
- (void)setGridViewDelegate:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

