//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SettingBaseViewController.h"

@class DelaySwitchSettingLogic;

@interface SettingDiscoverEntranceViewController : SettingBaseViewController
{
    struct map<unsigned long, unsigned int, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, unsigned int>>> m_mapRowToRowType;
    float settingDiscoverEntranceViewCellHeight;
    float settingDiscoverEntranceViewCellContentLeftMargin;
    float settingDiscoverEntranceViewCellIconSize;
    float settingDiscoverEntranceViewCellIconLabelInterval;
    float settingDiscoverEntranceViewCellLabelWidth;
    float settingDiscoverEntranceViewCellWidth;
    float settingDiscoverEntranceViewCellContentRightMargin;
    BOOL _hasChangedSwitch;
    DelaySwitchSettingLogic *_delaySwitchLogic;
}

@property(nonatomic) BOOL hasChangedSwitch; // @synthesize hasChangedSwitch=_hasChangedSwitch;
@property(retain, nonatomic) DelaySwitchSettingLogic *delaySwitchLogic; // @synthesize delaySwitchLogic=_delaySwitchLogic;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onSwitchChanged:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)makeSwitchCell:(id)arg1 row:(unsigned int)arg2;
- (void)reloadData;
- (void)resetRowType;
- (id)tableView;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)init;

@end

