//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ILinkEventExt.h"
#import "MMRTCMenuResponderDelegate.h"
#import "MMRichTextSelectEventDelegate.h"
#import "TransitioningAnimationDelegate.h"
#import "scrollViewDelegate.h"

@class CTRichTextView, CrossfadeAnimationController, MMRichTextCoverView, MMScrollView, NSString, UIButton, UIFont, UIView;

@interface TextFloatViewController : MMUIViewController <TransitioningAnimationDelegate, MMRTCMenuResponderDelegate, ILinkEventExt, scrollViewDelegate, MMRichTextSelectEventDelegate>
{
    UIView *m_oBackView;
    UIButton *m_view;
    MMScrollView *m_oScrollView;
    CTRichTextView *m_oRichTextView;
    id <ILinkEventExt> m_linkDelegate;
    struct CGPoint m_origin;
    id <TextFloatPreviewDelegate> m_delegate;
    BOOL _bNeedRebuildTextView;
    BOOL m_bHidden;
    MMRichTextCoverView *m_oRichTextCoverView;
    CrossfadeAnimationController *m_transitionInstance;
    BOOL m_allowAutorotate;
    struct CGRect m_originFrame;
    NSString *_nsContent;
    UIFont *_oFont;
    unsigned int _parserType;
}

@property(nonatomic) unsigned int parserType; // @synthesize parserType=_parserType;
@property(retain, nonatomic) UIFont *oFont; // @synthesize oFont=_oFont;
@property(retain, nonatomic) NSString *nsContent; // @synthesize nsContent=_nsContent;
@property(nonatomic) __weak id <TextFloatPreviewDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (id)getCurrentViewController;
- (id)getScrollView;
- (void)onRichTextViewExit;
- (BOOL)respondsToSelector:(SEL)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (void)viewWillBeDismissed:(BOOL)arg1;
- (void)viewDidBePresented:(BOOL)arg1;
- (void)viewWillDismiss:(BOOL)arg1;
- (void)viewWillPresent:(BOOL)arg1;
- (void)hideWithAnimate:(BOOL)arg1;
- (void)touchesEnded_ScrollView:(id)arg1 withEvent:(id)arg2;
- (void)onSingleTap;
- (void)onSingleTapWithPoint:(struct CGPoint)arg1;
- (void)setOriginFrame:(struct CGRect)arg1;
- (void)setContent:(id)arg1;
- (void)updateTextView;
- (void)setLinkDelegate:(id)arg1;
- (void)layoutSubviews;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;
- (void)showTransitioningAnimationCompleted;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

