//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VoiceInputLanguageConfig : NSObject
{
    BOOL hadShowSelectGuideView;
    long selectedLanguageSupportType;
    long lastUsedLanguageType;
}

+ (void)initialize;
@property(nonatomic) BOOL hadShowSelectGuideView; // @synthesize hadShowSelectGuideView;
@property(nonatomic) long lastUsedLanguageType; // @synthesize lastUsedLanguageType;
@property(nonatomic) long selectedLanguageSupportType; // @synthesize selectedLanguageSupportType;
- (id)description;
- (const map_69681069 *)getValueTagIndexMap;
- (id)getValueTypeTable;

@end

