//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QAnnotationView.h"

@class NSDictionary, WAMapCalloutView;

@interface WAMapAnnotationView : QAnnotationView
{
    BOOL _fixedCallout;
    NSDictionary *_calloutParam;
    id _calloutTarget;
    SEL _calloutAction;
    unsigned int _calloutControlEvents;
    WAMapCalloutView *_customCalloutView;
}

@property(retain, nonatomic) WAMapCalloutView *customCalloutView; // @synthesize customCalloutView=_customCalloutView;
@property(nonatomic) unsigned int calloutControlEvents; // @synthesize calloutControlEvents=_calloutControlEvents;
@property(nonatomic) SEL calloutAction; // @synthesize calloutAction=_calloutAction;
@property(nonatomic) __weak id calloutTarget; // @synthesize calloutTarget=_calloutTarget;
@property(retain, nonatomic) NSDictionary *calloutParam; // @synthesize calloutParam=_calloutParam;
@property(nonatomic) BOOL fixedCallout; // @synthesize fixedCallout=_fixedCallout;
- (void).cxx_destruct;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)onClick;
- (void)addCalloutView;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)addCalloutTarget:(id)arg1 action:(SEL)arg2 forControlEvents:(unsigned int)arg3;

@end

