//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMTipsViewController.h"

@interface WATipsViewController : MMTipsViewController
{
    BOOL _currentUseBlackStatusBar;
    BOOL m_bUseBlackStatusBar;
}

@property(nonatomic) BOOL m_bUseBlackStatusBar; // @synthesize m_bUseBlackStatusBar;
- (void)showWithAnimated:(int)arg1;
- (void)setUseBlackStatusBar:(BOOL)arg1;
- (BOOL)useBlackStatusbar;

@end

