//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMToastViewController.h"

@interface WAToastViewController : MMToastViewController
{
    BOOL _currentUseBlackStatusBar;
}

- (void)showWithAnimated:(int)arg1;
- (void)setUseBlackStatusBar:(BOOL)arg1;
- (BOOL)useBlackStatusbar;

@end

