//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCBaseControlMgr.h"

#import "MMKernelExt.h"

@class NSString, UIViewController, UIWindow;

@interface WCAccountManualLoginControlMgr : WCBaseControlMgr <MMKernelExt>
{
    struct map<unsigned long long, NSString *, std::__1::less<unsigned long long>, std::__1::allocator<std::__1::pair<const unsigned long long, NSString *>>> m_mapStatus;
    UIViewController *m_firstViewController;
    UIWindow *m_window;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)reportLogoutSwitchToOtherAccount;
- (void)reportLogoutSwitchToOtherMethodToLogin;
- (void)reportLogoutDefaultPhoneOrNot:(BOOL)arg1;
- (void)reportPwdSwitchToVerifyOrReverse:(BOOL)arg1;
- (void)reportPhoneSwitchToOthersOrReverse:(BOOL)arg1;
- (void)reportADID;
- (BOOL)isRestTime:(id)arg1;
- (unsigned long long)getReportTime;
- (void)reportClickStream:(id)arg1;
- (unsigned long)startNewPhoneLoginLogic:(id)arg1 Data:(id)arg2;
- (unsigned long)startCreateVoicePrintLogic:(id)arg1 Data:(id)arg2;
- (unsigned long)startInviteLogic:(id)arg1 Data:(id)arg2;
- (unsigned long)startRegisterLogic:(id)arg1 Data:(id)arg2;
- (unsigned long)startSecurityCenterLogic:(id)arg1 Data:(id)arg2;
- (unsigned long)startFacebookLogic:(id)arg1 Data:(id)arg2;
- (unsigned long)startPhoneLoginLogic:(id)arg1 Data:(id)arg2;
- (unsigned long)startQRCodeLoginLogic:(id)arg1 Data:(id)arg2;
- (unsigned long)startOneClickLoginLogic:(id)arg1 Data:(id)arg2;
- (unsigned long)startLoginLogic:(id)arg1 Data:(id)arg2;
- (id)showAlertWithTitle:(id)arg1 message:(id)arg2 btnTitle:(id)arg3 target:(id)arg4 sel:(SEL)arg5 btnTitle:(id)arg6 target:(id)arg7 sel:(SEL)arg8 btnTitle:(id)arg9 target:(id)arg10 sel:(SEL)arg11 status:(unsigned long)arg12;
- (id)showAlertWithTitle:(id)arg1 message:(id)arg2 btnTitle:(id)arg3 target:(id)arg4 sel:(SEL)arg5 btnTitle:(id)arg6 target:(id)arg7 sel:(SEL)arg8 status:(unsigned long)arg9;
- (id)showAlertWithTitle:(id)arg1 message:(id)arg2 btnTitle:(id)arg3 target:(id)arg4 sel:(SEL)arg5 status:(unsigned long)arg6;
- (void)dismissAlertView:(id)arg1 buttonIndex:(id)arg2;
- (void)reportExitAlert:(id)arg1;
- (void)reportEnterAlert:(id)arg1;
- (void)reportClickAction:(unsigned long)arg1;
- (void)reportClickAction:(unsigned long)arg1 styleID:(id)arg2;
- (id)getStatusName:(unsigned long)arg1;
- (void)switchLogin;
- (void)closeFirstView:(BOOL)arg1;
- (void)openFirstView:(id)arg1 withNavBarHidden:(BOOL)arg2;
- (void)setMainWindowRootView:(id)arg1;
- (void)openFirstView:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

