//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSString;

@interface WCPayLQTEnteranceInfo : NSObject <PBCoding>
{
    NSString *lct_wording;
    unsigned int lqt_state;
    NSString *lct_url;
}

+ (BOOL)saveLQTEnteranceInfo:(id)arg1;
+ (id)getLocalLQTEnteranceInfo;
+ (void)initialize;
@property(retain, nonatomic) NSString *lct_url; // @synthesize lct_url;
@property(nonatomic) unsigned int lqt_state; // @synthesize lqt_state;
@property(retain, nonatomic) NSString *lct_wording; // @synthesize lct_wording;
- (void).cxx_destruct;
- (const map_69681069 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

