//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseMessageViewModel.h"

@class NSString, UIColor, UIImage;

@interface WCPayThirdC2CMessageViewModel : WCPayBaseMessageViewModel
{
    UIImage *_m_miniIconImage;
}

+ (BOOL)canCreateMessageViewModelWithMessageWrap:(id)arg1;
@property(retain, nonatomic) UIImage *m_miniIconImage; // @synthesize m_miniIconImage=_m_miniIconImage;
- (void).cxx_destruct;
- (id)additionalAccessibilityDescription;
@property(readonly, nonatomic) UIColor *descColor;
@property(readonly, nonatomic) UIColor *titleColor;
@property(readonly, nonatomic) NSString *miniIconUrl;
@property(readonly, nonatomic) NSString *backgroundUrl;
- (id)iconUrl;
- (float)iconSize;
- (id)descText;
- (id)titleText;
- (id)sourceIcon;
- (void)setMiniIconImage:(id)arg1;
- (id)sourceTitle;
- (BOOL)isShowSourceView;
- (id)cellViewClassName;
- (struct CGSize)measureContentViewSize:(struct CGSize)arg1;

@end

