//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCUpdateResourceExt.h"

@class WCUpdateInfo;

@interface WCUpdateMgr : NSObject <WCUpdateResourceExt>
{
    WCUpdateInfo *_patchInfo;
}

+ (id)getInstance;
- (void).cxx_destruct;
- (_Bool)_loadBundleWithoutCheck:(id)arg1;
- (void)exitOnEnteringBackground;
- (void)setNewClientVersionInUserDefault:(unsigned long)arg1;
- (void)clearNewClientVersionInUserDefault;
- (unsigned long)newClientVersion;
- (void)runPatch;
- (id)getPatchInfo;
- (void)onPatchResDeleteFinish;
- (void)onPatchResUpdateFinish:(unsigned int)arg1;
- (void)dealloc;
- (void)loadDiscoverEntranceView;
- (void)forceUpdate:(unsigned long)arg1;
- (void)registerExtension;
- (_Bool)loadBundle:(id)arg1;
- (void)loadAndExecute;
- (id)init;

@end

