//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IFavAudioRecorderExt.h"
#import "IRecordPermissionCheckExt.h"
#import "MMService.h"
#import "SimpleRecordBufferDelegate.h"

@class FavAudioRecorder, MMTimer, NSMutableData, NSString, SimpleAudioRecorder;

@interface WebviewRecorderManager : MMService <SimpleRecordBufferDelegate, MMService, IFavAudioRecorderExt, IRecordPermissionCheckExt>
{
    FavAudioRecorder *_recorder;
    int _recordStatus;
    NSString *_lastFilePath;
    unsigned int _startRecordTime;
    unsigned int _endRecordTime;
    MMTimer *_recordTimer;
    int _stopReason;
    int _recordTimeoutValue;
    SimpleAudioRecorder *m_pcmRecorder;
    NSMutableData *m_pcmDataOrigin;
    NSMutableData *m_pcmDataFixed;
    int m_pcmFixIndex;
    void *m_pstsplitjoint;
    NSString *_lastPcmFixPath;
}

@property(retain, nonatomic) NSString *lastPcmFixPath; // @synthesize lastPcmFixPath=_lastPcmFixPath;
@property(retain, nonatomic) NSString *lastFilePath; // @synthesize lastFilePath=_lastFilePath;
- (void).cxx_destruct;
- (double)simpleRateForBuffer;
- (unsigned long)channlesPerFrame;
- (unsigned long)framesPerPacket;
- (unsigned long)bitsPerChannel;
- (void)onAudioBufferRecordEnd;
- (void)outputPeakPower:(float)arg1;
- (void)outputPcmBuffer:(void *)arg1 bufferSize:(unsigned long)arg2;
- (void)stopPcmRecord;
- (BOOL)startPcmRecord;
- (void)OnFavFinishRecord:(id)arg1 VoiceFmt:(unsigned long)arg2;
- (void)OnFavBeginRecording:(int)arg1;
- (BOOL)internalStopRecord;
- (void)stopTime;
- (void)onTimeCount;
- (void)notifyFinishRecordOnMainThread:(id)arg1;
- (void)notifyRecordTimeTooShortOnMainThread;
- (void)notifyStartRecordOnMainThread:(id)arg1;
- (BOOL)endRecord;
- (BOOL)stopRecord;
- (BOOL)startRecord:(int)arg1 duration:(unsigned int)arg2;
- (int)getRecordStatus;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

