//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WKProxyHelper : NSObject
{
}

+ (void)checkProxyInfoWithCompletion:(CDUnknownBlockType)arg1;
+ (void)cleanupCrashState;
+ (void)downloadProxyInfoIfNecessary;
+ (void)resetStateWhenAppEnterBackground;
+ (void)crashProtectionEnd;
+ (void)crashProtectionBegin;
+ (BOOL)isProxyAvailable;
+ (BOOL)enableWKProxy:(id *)arg1;
+ (void)clearProxyMemory;
+ (BOOL)setProxyInfoLocallyWithError:(id *)arg1;
+ (void)downloadProxyInfo;
+ (void)initialize;
+ (BOOL)shouldDownloadWKProxy;
+ (id)phoneID;
+ (BOOL)isReportWithMemCmpEnabled;
+ (void)setReportEnabled:(BOOL)arg1;
+ (BOOL)isReportEnabled;
+ (void)setCrashReported:(BOOL)arg1;
+ (BOOL)isCrashHasReported;
+ (BOOL)isDetectedCrashWithTimes:(int)arg1;
+ (BOOL)isDetectedCrash;
+ (int)proxyResult;
+ (void)setProxyResult:(int)arg1;
+ (void)setProxyActionState:(int)arg1;
+ (int)proxyActionState;
+ (void)finishActionWithResult:(int)arg1;
+ (void)checkProxyActionState;
+ (void)downloadWKProxyInfoWithCompletion:(CDUnknownBlockType)arg1;
+ (BOOL)setWithProxyInfo:(id)arg1;
+ (BOOL)isProxyInfoValid:(id)arg1;
+ (void)registerMttSchemePrivate;
+ (const struct mach_header *)getWebkitHeader;
+ (id)generateMemory;
- (id)init;

@end

